[package]
name = "notion-zh_CN"
version = "2.4.20"
edition = "2021"

[workspace]
members = [
    "update_intl",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

